Repository intel/cloud-native-ai-pipeline, pull requests merged in 2023-07, with the labels that each got.

#27 .github/pr-check-license.yaml: fix the license check issue
  .github/license_check.ini
  .github/workflows/pr-license-check.yaml
Labels: ci/cd

#25 protobuf: add the frame proto and defination
  cnap/core/generated/core/protobuf/frame_pb2.py
  cnap/core/protobuf/frame.proto
  cnap/requirements.txt
Labels: feature

#30 model.py: design and create the basic model info class
  cnap/core/model.py
Labels: feature

#28 cnap/core: add the implementation for stream provider
  cnap/core/stream.py
  cnap/requirements.txt
Labels: feature

#37 pylint: fix the python code lint issues
  cnap/core/filedb.py
  cnap/core/model.py
  cnap/core/stream.py
Labels: ci/cd

#33 preprocessor.py: add the preprocessor for inference
  cnap/core/processors/__init__.py
  cnap/core/processors/preprocessor.py
Labels: feature

#35 postprocessor.py: add the postprocessor for inference
  cnap/core/processors/category_list.py
  cnap/core/processors/postprocessor.py
Labels: feature

#39 core/rtdb.py: handle the unexpected errors
  cnap/core/rtdb.py
Labels: enhancement

#36 cnap/core: add the implementation for frame class
  cnap/core/frame.py
Labels: feature

#38 README.md: Add a Note in README
  README.md
Labels: documentation

#40 rtdb.py: add reconnection to Redis when a connection error occurs
  cnap/core/rtdb.py
Labels: enhancement

#45 infereng.py: add the base inference engine implementation
  cnap/core/infereng.py
Labels: feature

#47 .gitignore: add the files to be ignored in repo
  .gitignore
Labels: enhancement

#43 cnap/core: add the implementation for inference queue client
  cnap/core/inferqueue.py
  cnap/requirements.txt
Labels: feature

#44 core/cnap: add the implementation for stream broker client
  cnap/core/streambroker.py
Labels: feature

#49 ui: add the VUE single page application for CNAP
  cnap/ui/.gitignore
  cnap/ui/.npmrc
  cnap/ui/README.md
  cnap/ui/index.html
  cnap/ui/package.json
  cnap/ui/public/CNAME
  cnap/ui/public/element-plus-logo-small.svg
  cnap/ui/public/favicon.svg
  cnap/ui/src/App.vue
  cnap/ui/src/api/frame.d.ts
  cnap/ui/src/api/frame.js
  cnap/ui/src/api/ppdb_api.ts
  cnap/ui/src/assets/carbon_footprint.png
  cnap/ui/src/assets/cnap_logo.png
  cnap/ui/src/assets/diverse_frameworks.png
  cnap/ui/src/assets/pipeline_cloud_native_design.png
  cnap/ui/src/assets/sample-video.png
  cnap/ui/src/assets/trusted_pipeline.png
  cnap/ui/src/components.d.ts
  cnap/ui/src/components/AppFooter.vue
  cnap/ui/src/components/AppHeader.vue
  cnap/ui/src/components/DetailView.vue
  cnap/ui/src/components/StreamView.vue
  cnap/ui/src/composables/dark.ts
  cnap/ui/src/composables/index.ts
  cnap/ui/src/env.d.ts
  cnap/ui/src/main.ts
  cnap/ui/src/proto
  cnap/ui/src/router.ts
  cnap/ui/src/store/index.ts
  cnap/ui/src/styles/element/dark.scss
  cnap/ui/src/styles/element/index.scss
  cnap/ui/src/styles/index.scss
  cnap/ui/src/views/Dashboard.vue
  cnap/ui/src/views/Overview.vue
  cnap/ui/src/views/Pipelines.vue
  cnap/ui/tsconfig.json
  cnap/ui/vite.config.ts
Labels: feature

#51 .github/pr-node-check.yaml: add the action to scan ui node code
  .github/workflows/pr-node-check.yaml
  README.md
Labels: ci/cd

#57 core/engines: add the tensorflow engine
  cnap/core/engines/__init__.py
  cnap/core/engines/tensorflow_engine.py
  cnap/requirements.txt
Labels: feature

#53 cnap/core: add the implementation for pipeline related classes
  cnap/core/pipeline.py
Labels: feature

#58 userv/uapp: add the basic micro app and service class
  cnap/userv/__init__.py
  cnap/userv/uapp.py
Labels: feature

#66 core/userv: add the implementation for streaming service
  cnap/userv/streaming.py
Labels: feature

#64 userv/inference: add the inference service
  cnap/userv/inference.py
Labels: feature

#60 userv/pipeline_server: add the pipeline server
  cnap/requirements.txt
  cnap/userv/pipeline_server.py
Labels: feature

#62 cnap/userv: add the implementation for websocket server
  cnap/requirements.txt
  cnap/userv/websocket_server.py
Labels: feature

#55 .github/workflows: add paths for github actions
  .github/workflows/pr-doclint.yaml
  .github/workflows/pr-license-check.yaml
  .github/workflows/pr-node-check.yaml
  .github/workflows/pr-pylint.yaml
  .github/workflows/pr-shell-check.yaml
Labels: ci/cd

#69 docs/resources: add the uml definitions and diagrams
  docs/resources/images/class_uml/engines/tensorflowengine.png
  docs/resources/images/class_uml/filedb.png
  docs/resources/images/class_uml/frame.png
  docs/resources/images/class_uml/infereng.png
  docs/resources/images/class_uml/inferqueue.png
  docs/resources/images/class_uml/model.png
  docs/resources/images/class_uml/pipeline.png
  docs/resources/images/class_uml/processors/postprocessor.png
  docs/resources/images/class_uml/processors/preprocessor.png
  docs/resources/images/class_uml/rtdb.png
  docs/resources/images/class_uml/stream.png
  docs/resources/images/class_uml/streambroker.png
  docs/resources/pumls/engines/tensorflowengine.puml
  docs/resources/pumls/filedb.puml
  docs/resources/pumls/frame.puml
  docs/resources/pumls/infereng.puml
  docs/resources/pumls/inferqueue.puml
  docs/resources/pumls/model.puml
  docs/resources/pumls/pipeline.puml
  docs/resources/pumls/processors/postprocessor.puml
  docs/resources/pumls/processors/preprocessor.puml
  docs/resources/pumls/rtdb.puml
  docs/resources/pumls/stream.puml
  docs/resources/pumls/streambroker.puml
  docs/resources/pumls/style.puml
Labels: documentation

#75 .github/pr-python-check.yaml: add the pydocstyle check
  .github/workflows/pr-python-check.yaml
Labels: ci/cd

#70 cnap: format codes using google docstring
  cnap/core/__init__.py
  cnap/core/engines/__init__.py
  cnap/core/engines/tensorflow_engine.py
  cnap/core/filedb.py
  cnap/core/frame.py
  cnap/core/infereng.py
  cnap/core/inferqueue.py
  cnap/core/model.py
  cnap/core/pipeline.py
  cnap/core/processors/__init__.py
  cnap/core/processors/category_list.py
  cnap/core/processors/postprocessor.py
  cnap/core/processors/preprocessor.py
  cnap/core/rtdb.py
  cnap/core/stream.py
  cnap/core/streambroker.py
  cnap/userv/__init__.py
  cnap/userv/inference.py
  cnap/userv/pipeline_server.py
  cnap/userv/streaming.py
  cnap/userv/uapp.py
  cnap/userv/websocket_server.py
Labels: enhancement

#76 README.md: fix with the github workflow
  README.md
Labels: documentation

#78 container: create dockerfiles for micro services
  cnap/userv/streaming.py
  container/cnap-inference/Dockerfile
  container/cnap-ppdb/Dockerfile
  container/cnap-spa/Dockerfile
  container/cnap-streaming/Dockerfile
  container/cnap-wss/Dockerfile
Labels: feature

#80 tools: add the docker image build script
  tools/docker_image_manager.sh
Labels: enhancement

#82 README.md: add guide for building docker images
  .github/cspell.json
  README.md
Labels: documentation

#84 core/metrics.py: add the metrics framework
  cnap/core/engines/tensorflow_engine.py
  cnap/core/metrics.py
  cnap/requirements.txt
  cnap/userv/inference.py
Labels: feature

#88 userv/streaming.py: fix the frames input fps issue
  cnap/userv/streaming.py
Labels: enhancement
