Repository intel/cloud-native-ai-pipeline, pull requests merged in 2023-08, with the labels that each got.

#86 cnap: add inference fps for metrics export and spa display
  cnap/core/engines/tensorflow_engine.py
  cnap/core/pipeline.py
  cnap/core/stream.py
  cnap/userv/inference.py
  cnap/userv/pipeline_server.py
  container/cnap-inference/Dockerfile
Labels: feature

#90 tests: add the basic unit test
  cnap/requirements-test.txt
  tests/__init__.py
  tests/core/__init__.py
  tests/core/test_filedb.py
  tests/core/test_frame.py
  tests/core/test_infereng.py
  tests/core/test_inferqueue.py
  tests/core/test_metrics.py
  tests/core/test_model.py
  tests/core/test_pipeline.py
  tests/core/test_rtdb.py
  tests/core/test_stream.py
  tests/core/test_streambroker.py
  tests/userv/__init__.py
  tests/userv/test_inference.py
  tests/userv/test_pipeline_server.py
  tests/userv/test_streaming.py
  tests/userv/test_uapp.py
  tests/userv/test_websocket_server.py
Labels: enhancement, feature

#93 cicd: add the scan for tests files
  .github/workflows/pr-license-check.yaml
  .github/workflows/pr-python-check.yaml
  tests/core/test_filedb.py
Labels: ci/cd

#95 cicd: update the pylint configuration
  .github/pylintrc
Labels: ci/cd

#96 .github/license_check.ini: update the authorized_licenses
  .github/license_check.ini
Labels: ci/cd

#92 cnap/core:add qat_zip to compress/decompress the frame
  cnap/core/qat.py
  cnap/core/qat_params.py
Labels: feature

#100 cicd: add the coverage check for tests
  .github/workflows/pr-python-check.yaml
  .gitignore
  cnap/requirements-test.txt
Labels: ci/cd

#103 cicd: move coverage report to log
  .github/workflows/pr-python-check.yaml
Labels: ci/cd

#102 helm: add the helm chart for CNAP micro service
  helm/inference/.helmignore
  helm/inference/Chart.yaml
  helm/inference/templates/NOTES.txt
  helm/inference/templates/_helpers.tpl
  helm/inference/templates/deployment.yaml
  helm/inference/values.yaml
  helm/pipelineapi/.helmignore
  helm/pipelineapi/Chart.yaml
  helm/pipelineapi/templates/NOTES.txt
  helm/pipelineapi/templates/_helpers.tpl
  helm/pipelineapi/templates/deployment.yaml
  helm/pipelineapi/templates/service.yaml
  helm/pipelineapi/templates/tests/test-connection.yaml
  helm/pipelineapi/values.yaml
  helm/redis-exporter/.helmignore
  helm/redis-exporter/Chart.yaml
  helm/redis-exporter/dashboards/grafana_prometheus_redis_dashboard.json
  helm/redis-exporter/templates/NOTES.txt
  helm/redis-exporter/templates/_helpers.tpl
  helm/redis-exporter/templates/configmap.yaml
  helm/redis-exporter/templates/deployment.yaml
  helm/redis-exporter/templates/service.yaml
  helm/redis-exporter/templates/servicemonitor.yaml
  helm/redis-exporter/templates/tests/test-connection.yaml
  helm/redis-exporter/values.yaml
  helm/redis/.helmignore
  helm/redis/Chart.yaml
  helm/redis/templates/NOTES.txt
  helm/redis/templates/_helpers.tpl
  helm/redis/templates/configmap.yaml
  helm/redis/templates/deployment.yaml
  helm/redis/templates/service.yaml
  helm/redis/templates/tests/test-connection.yaml
  helm/redis/values.yaml
  helm/stream/.helmignore
  helm/stream/Chart.yaml
  helm/stream/templates/NOTES.txt
  helm/stream/templates/_helpers.tpl
  helm/stream/templates/deployment.yaml
  helm/stream/values.yaml
  helm/ui/.helmignore
  helm/ui/Chart.yaml
  helm/ui/templates/NOTES.txt
  helm/ui/templates/_helpers.tpl
  helm/ui/templates/deployment.yaml
  helm/ui/templates/service.yaml
  helm/ui/values.yaml
  helm/websocket/.helmignore
  helm/websocket/Chart.yaml
  helm/websocket/templates/NOTES.txt
  helm/websocket/templates/_helpers.tpl
  helm/websocket/templates/deployment.yaml
  helm/websocket/templates/service.yaml
  helm/websocket/templates/tests/test-connection.yaml
  helm/websocket/values.yaml
Labels: feature

#98 test_frame.py: add unit test and small fixes for Frame module
  cnap/core/frame.py
  tests/core/test_frame.py
Labels: enhancement, feature

#105 userv/inference: add latency metrics between streaming and inference
  cnap/userv/inference.py
Labels: feature

#97 test_pipeline.py: add unit test for pipeline module
  tests/core/test_pipeline.py
Labels: enhancement, feature

#94 test_rtdb.py: add unit test for runtime database module.
  cnap/requirements-test.txt
  tests/core/test_filedb.py
  tests/core/test_frame.py
  tests/core/test_infereng.py
  tests/core/test_inferqueue.py
  tests/core/test_metrics.py
  tests/core/test_model.py
  tests/core/test_rtdb.py
  tests/core/test_stream.py
  tests/core/test_streambroker.py
  tests/userv/test_inference.py
  tests/userv/test_pipeline_server.py
  tests/userv/test_streaming.py
  tests/userv/test_uapp.py
  tests/userv/test_websocket_server.py
Labels: enhancement, feature

#107 helm/inference: add deployment file for `service` and `servicemonitor`
  helm/inference/templates/deployment.yaml
  helm/inference/templates/service.yaml
  helm/inference/templates/servicemonitor.yaml
  helm/inference/values.yaml
Labels: feature

#111 README.md: update the guide to install using helm
  .github/cspell.json
  README.md
Labels: documentation

#110 tools/helm-manager: add user friendly tool to use helm chart
  tools/helm_manager.sh
Labels: enhancement

#109 userv: Add integrated methods for QAT
  cnap/core/crypto/__init__.py
  cnap/core/crypto/qat.py
  cnap/core/crypto/qat_params.py
  cnap/core/crypto/zip.py
  cnap/core/frame.py
  cnap/core/inferqueue.py
  cnap/userv/inference.py
  cnap/userv/streaming.py
Labels: feature

#120 ui: add real FPS data to the echarts on SPA
  cnap/ui/src/components/DetailView.vue
  cnap/ui/src/store/index.ts
  cnap/ui/src/views/Pipelines.vue
Labels: feature

#123 tools/helm_manager: add the namespace configuration
  tools/helm_manager.sh
Labels: enhancement

#122 ui: add Grafana tab in SPA and fix url update issue
  cnap/ui/src/App.vue
  cnap/ui/src/components/AppHeader.vue
  cnap/ui/src/router.ts
  cnap/ui/src/store/index.ts
  cnap/ui/src/views/Dashboard.vue
  cnap/ui/src/views/Grafana.vue
  cnap/ui/src/views/Pipelines.vue
  k8s-manifests/grafana/configmaps/cnap-inference-dashboard-cm.yaml
  k8s-manifests/grafana/configmaps/grafana-config-cm.yaml
  k8s-manifests/grafana/patches/grafana-patch.yaml
Labels: feature

#129 grafana: add the keda dashboard of grafana
  k8s-manifests/grafana/configmaps/keda-dashboard-cm.yaml
  k8s-manifests/grafana/dashboards/keda.json
Labels: enhancement
