Repository intel/cloud-native-ai-pipeline, pull requests merged in 2023-06, with the labels that each got.

#14 .github/pr-pylint.yaml: add python lint scan CI
  .github/pylintrc
  .github/workflows/pr-pylint.yaml
  README.md
  cnap/requirements.txt
Labels: ci/cd

#15 .github/pr-check-license.yaml: add license check scan CI
  .github/.license_check.ini
  .github/workflows/pr-license-check.yaml
  README.md
Labels: ci/cd

#16 README.md: add badge for document spell check
  README.md
Labels: documentation

#17 SECURITY.md: Change file name to SECURITY.md according to common practice
  SECURITY.md
Labels: documentation

#18 .github/pr-shell-check.yaml: add shell code scan CI
  .github/workflows/pr-shell-check.yaml
  README.md
Labels: ci/cd

#19 README.md: add more usages of cnap
  README.md
  docs/cnap-uses.png
Labels: documentation

#21 tools: add the video downloader to fetch video from remote
  .github/workflows/pr-shell-check.yaml
  tools/common.sh
  tools/video_downloader.sh
Labels: enhancement

#22 cnap/core: add the implementation for filedatabase
  cnap/core/filedb.py
Labels: feature
