Repository intel/cloud-native-ai-pipeline, pull requests merged in 2023-09, with the labels that each got.

#126 container: Add redis + DTO image for DSA.
  container/cnap-redis/Dockerfile
  container/cnap-redis/patches/idxd-reset.patch
  container/cnap-redis/patches/idxd.h
  container/cnap-redis/patches/redis_dto.patch
  container/cnap-redis/patches/test_runner_disable_shared_queues.patch
  container/cnap-redis/redis.conf
  helm/redis/Chart.yaml
  helm/redis/templates/deployment.yaml
  helm/redis/values.yaml
Labels: feature

#130 keda: add the keda scale job for inference based on drop fps
  k8s-manifests/keda/infer_scale.yaml
Labels: integration

#132 ui: add latency data to the echarts
  cnap/core/frame.py
  cnap/core/generated/core/protobuf/frame_pb2.py
  cnap/core/protobuf/frame.proto
  cnap/ui/src/api/frame.d.ts
  cnap/ui/src/api/frame.js
  cnap/ui/src/components/DetailView.vue
  cnap/ui/src/components/StreamView.vue
  cnap/userv/inference.py
  docs/resources/images/class_uml/frame.png
  docs/resources/pumls/frame.puml
  tests/core/test_frame.py
Labels: feature

#133 keda: add the keda service monitor and update scale
  k8s-manifests/keda/infer_scale.yaml
  k8s-manifests/keda/keda-service-monitor.yaml
Labels: integration

#134 Prometheus: configure the prometheus to watch all namespace
  k8s-manifests/prometheus/ClusterRole-All.yaml
Labels: integration

#135 README.md: revise Note description according to feedback
  README.md
Labels: documentation

#136 test_infereng.py: add unit test for inference engine module
  cnap/core/filedb.py
  cnap/core/frame.py
  cnap/core/infereng.py
  cnap/core/rtdb.py
  tests/core/test_infereng.py
Labels: enhancement

#138 cnap/core: add model provider to get model info and download model
  cnap/core/model.py
  cnap/core/modelprovider.py
  cnap/requirements.txt
  cnap/userv/inference.py
  tests/core/test_infereng.py
Labels: feature

#142 test: add unit test for streambroker module
  cnap/core/streambroker.py
  cnap/requirements-test.txt
  tests/core/conftest.py
  tests/core/test_frame.py
  tests/core/test_infereng.py
  tests/core/test_pipeline.py
  tests/core/test_rtdb.py
  tests/core/test_streambroker.py
Labels: enhancement

#145 .github/workflows: add the check for k8s-manifests
  .github/workflows/pr-shell-check.yaml
Labels: ci/cd

#144 docs: Add Redis DSA offloading README
  docs/enable_dsa_offloading.md
  k8s-manifests/plugin/dsa/config_dsa/configs/1e1w-d.conf
  k8s-manifests/plugin/dsa/config_dsa/configs/1e1w-s.conf
  k8s-manifests/plugin/dsa/config_dsa/configs/4e1w-d.conf
  k8s-manifests/plugin/dsa/config_dsa/configs/4e4w-d.conf
  k8s-manifests/plugin/dsa/config_dsa/configs/4e8w-d.conf
  k8s-manifests/plugin/dsa/config_dsa/setup_dsa.sh
Labels: documentation, integration

#149 infereng.py: add the cpu-amx accelerator
  cnap/core/infereng.py
Labels: enhancement

#150 tools: add the support for download the images to k8s ns
  tools/docker_image_manager.sh
Labels: enhancement

#157 html: update the context
  _images/cnap-uses.png
  _images/cnap_arch.png
  _sources/core/core.rst.txt
  _sources/enable_dsa_offloading.md.txt
  _sources/index.rst.txt
  core/core.engines.html
  core/core.html
  core/core.processors.html
  core/modules.html
  enable_dsa_offloading.html
  genindex.html
  index.html
  objects.inv
  py-modindex.html
  searchindex.js
  userv/userv.html
Labels: documentation
