Repository intel/cloud-native-ai-pipeline, pull requests merged in 2024-01, with the labels that each got.

#177 doc: add QAT integration documentation
  docs/enable_qat_offloading.md
Labels: documentation

#180 .github/workflow: Add the contributor list
  .github/workflows/contributor-list.yaml
  README.md
Labels: ci/cd

#181 README.md: enhance README to make it clearer
  README.md
Labels: documentation

#179 postprocessor.py: fix NumPy array issue when using latest opencv release
  cnap/core/processors/postprocessor.py
Labels: bug

#184 workflow: fix the token permission
  .github/workflows/contributor-list.yaml
Labels: ci/cd
